<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Expected url https://www.lambdatest.com/integrations is present]]>
    </line>
    <line>
      <![CDATA[Expected url https://www.lambdatest.com/integrations is present]]>
    </line>
    <line>
      <![CDATA[The URl is same as Expected(https://community.lambdatest.com/)]]>
    </line>
    <line>
      <![CDATA[The URl is same as Expected(https://community.lambdatest.com/)]]>
    </line>
  </reporter-output>
  <suite started-at="2023-06-15T07:44:18Z" name="LamdaTestSuite" finished-at="2023-06-15T07:44:58Z" duration-ms="39413">
    <groups>
    </groups>
    <test started-at="2023-06-15T07:44:18Z" name="Chrome_Windows10_Test" finished-at="2023-06-15T07:44:55Z" duration-ms="36460">
      <class name="com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test">
        <test-method is-config="true" signature="setUp(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test@1caa0244]" started-at="2023-06-15T13:14:18Z" name="setUp" finished-at="2023-06-15T13:14:37Z" duration-ms="18285" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[86.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[WIN10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="ScenarioLTC_Test()[pri:0, instance:com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test@1caa0244]" started-at="2023-06-15T13:14:37Z" name="ScenarioLTC_Test" finished-at="2023-06-15T13:14:54Z" duration-ms="17863" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Page title is not as expected expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Page title is not as expected expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test.ScenarioLTC_Test(LamdaTestAssesmentAdvanced_1Test.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Expected url https://www.lambdatest.com/integrations is present]]>
            </line>
            <line>
              <![CDATA[The URl is same as Expected(https://community.lambdatest.com/)]]>
            </line>
          </reporter-output>
        </test-method> <!-- ScenarioLTC_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test@1caa0244]" started-at="2023-06-15T13:14:54Z" name="tearDown" finished-at="2023-06-15T13:14:55Z" duration-ms="294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test -->
    </test> <!-- Chrome_Windows10_Test -->
    <test started-at="2023-06-15T07:44:18Z" name="Edge_Mac_Test" finished-at="2023-06-15T07:44:58Z" duration-ms="39413">
      <class name="com.lamdatest.tests.LamdaTestAssesmentAdvanced_2Test">
        <test-method is-config="true" signature="setUp(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.lamdatest.tests.LamdaTestAssesmentAdvanced_2Test@43df23d3]" started-at="2023-06-15T13:14:18Z" name="setUp" finished-at="2023-06-15T13:14:32Z" duration-ms="13285" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[87.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[macOS Sierra]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="ScenarioLTC_Test()[pri:0, instance:com.lamdatest.tests.LamdaTestAssesmentAdvanced_2Test@43df23d3]" started-at="2023-06-15T13:14:32Z" name="ScenarioLTC_Test" finished-at="2023-06-15T13:14:57Z" duration-ms="25781" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Page title is not as expected expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Page title is not as expected expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lamdatest.tests.LamdaTestAssesmentAdvanced_2Test.ScenarioLTC_Test(LamdaTestAssesmentAdvanced_2Test.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Expected url https://www.lambdatest.com/integrations is present]]>
            </line>
            <line>
              <![CDATA[The URl is same as Expected(https://community.lambdatest.com/)]]>
            </line>
          </reporter-output>
        </test-method> <!-- ScenarioLTC_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.lamdatest.tests.LamdaTestAssesmentAdvanced_2Test@43df23d3]" started-at="2023-06-15T13:14:57Z" name="tearDown" finished-at="2023-06-15T13:14:58Z" duration-ms="335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.lamdatest.tests.LamdaTestAssesmentAdvanced_2Test -->
    </test> <!-- Edge_Mac_Test -->
  </suite> <!-- LamdaTestSuite -->
</testng-results>
