<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PAVANKUMAR" failures="1" tests="1" name="com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test" time="36.442" errors="0" timestamp="15 Jun 2023 07:44:58 GMT">
  <testcase classname="com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test" name="ScenarioLTC_Test" time="36.442">
    <failure message="The following asserts failed:
	Page title is not as expected expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Page title is not as expected expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test.ScenarioLTC_Test(LamdaTestAssesmentAdvanced_1Test.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- ScenarioLTC_Test -->
</testsuite> <!-- com.lamdatest.tests.LamdaTestAssesmentAdvanced_1Test -->
